config/routes.rb
Rails.application.routes.draw do
  # devise_for :controllers
  devise_for  :users, :controllers => {:registrations => "users/registrations"}

  resources :jobs

  resources :job_applications, :except => [:destroy]
  post '/job_applications/:id', to: 'job_applications#hire', as: 'hire'

  get "/search-results" => 'jobs#searched'
  # devise_for :employers, :controllers => {:registrations => "users/registrations"}
  # devise_for :employees
  resources :employers, :only => [:show]
  resources :employees, :only => [:show]

  root "static#homepage"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/employee.rb
class Employee < ApplicationRecord
  mount_uploader :image, ProfilePicUploader

  has_one :user
  has_many :job_applications
  has_many :jobs, through: :job_applications
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
    average_rating_employee
    latest_three_reviews
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:name, :image)
    end

    def average_rating_employee
      @employee = Employee.find(params[:id])
      @total_rating = 0
      @total_reviews = 0
      @employee.job_applications.where("status" == "successful").each do |application|
          @total_rating += application.rating_employee.to_i
          if application.rating_employee
          @total_reviews += 1
          end
      end
      if @total_reviews.to_i > 0
      @average_rating = (@total_rating / @total_reviews).round(2)
      else
        @average_rating = 0
      end
    end

    def latest_three_reviews
      @employee = Employee.find(params[:id])
      @all_reviews = []
      @employee.job_applications.each do |app|
        if app.rating_employee
          @all_reviews << app
        end
      end
      @recent_reviews = @all_reviews.sort_by {|review| review.updated_at}
      @recent_reviews.reverse!.take(3)
    end

end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_for(employee) do |f| %>
  <% if employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<h1>Employees</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.name %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee', new_employee_path %>

app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<%= render '/partials/employee-profile' %>
<%if @recent_reviews%>
<div class="card-deck">
  <%@recent_reviews.each do |review|%>
  <div class="card">
    <div class="card-block">
      <h4 class="card-title"><span id="star-rating"></span><span id="rating">Rating: <%=review.rating_employee%></span></h4>
      <p class="card-text"><p><i>"<%=review.review_employee%>"</i></p>
      <p><%=review.job.employer.company%>, <%=review.updated_at.strftime("%m/%d/%y")%></p>
      </p>
    </div>
  </div>
  <%end%>
</div>
<%end%>
<br />
<div class="container-fluid">
  <% if current_user.id == @employee.user.id %>
  <%= link_to 'Edit', edit_user_registration_path(@employee), :class =>"btn btn-primary"%> |
  <% end %>
  <%= link_to 'Back', jobs_path, :class =>"btn btn-primary"%>
</div>