config/routes.rb
Rails.application.routes.draw do
  # devise_for :controllers
  devise_for  :users, :controllers => {:registrations => "users/registrations"}

  resources :jobs

  resources :job_applications, :except => [:destroy]
  post '/job_applications/:id', to: 'job_applications#hire', as: 'hire'

  get "/search-results" => 'jobs#searched'
  # devise_for :employers, :controllers => {:registrations => "users/registrations"}
  # devise_for :employees
  resources :employers, :only => [:show]
  resources :employees, :only => [:show]

  root "static#homepage"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :employer
  has_many :job_applications, dependent: :destroy
  has_many :employees, through: :job_applications
  validates :title, presence: true
  validates :description, presence: true
  validates :wage, numericality: { only_integer: true }
  validates :contact_person, presence: true
  validates :contact_email, presence: true
  validates :job_type, presence: true
  validates :time_commitment, numericality: true
  validates :location, presence: true
  validates :positions, presence: true, numericality: { only_integer: true }
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # only employers can create new jobs
  before_action :employer?, only: [:new]
  # only employers who created the jobs can crud their jobs
  before_action :own_job?, only: [:edit, :update, :destroy]
  # employers cannot edit or delete the job after the job has been filled
  #before_action :job_filled?, only: [:edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all
    if current_user.role == 'employee'

      @job_applications_made = current_user.employee.job_applications
      @jobs_applied = @job_applications_made.map {|application_made| application_made.job}
      puts "the jobs applied array is #{@jobs_applied}"
      @jobs_not_applied = []
      @jobs.each do |job|
        if(@jobs_applied.include?(job)==false)
          @jobs_not_applied << job
        end
      end

      @job_opportunities = []
      @vacancies = []
      @jobs_not_applied.each do |job|
        hired_count = JobApplication.where(job_id: job.id, status: 'Successful').count
        if (job.positions - hired_count > 0)
          @job_opportunities << job
          @vacancies << job.positions - hired_count
        end
      puts "the jobs not applied array is #{@jobs_not_applied}"
      end
    else
      @jobs = current_user.employer.jobs
      @hired_list = []
      @vacancies_list = []
      @jobs.each do |job|
        hired_count = JobApplication.where(job_id: job.id, status: 'Successful').count
        @hired_list << hired_count
        @vacancies_list << job.positions - hired_count
      end
    end
    @all_jobs = []
    @jobs.each { |job| @all_jobs.push(job.title) }
  end

  def searched
    if params[:search] == '' || params[:search] == nil
      @jobs_searched = []
      respond_to do |format|
        format.html
        format.js
      end
    else
      @jobs_searched = search(params[:search])
      respond_to do |format|
        format.html
        format.js
      end
    end
    puts "jobs searched are #{@jobs_searched.inspect}"
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
    @job = Job.find(params[:id])
    @job_applications = JobApplication.where(job_id: params[:id])
    @hired = JobApplication.where(job_id: params[:id], status: 'Successful')
    @vacancies = @job.positions - @hired.length
  end

  # GET /jobs/new
  def new
    p current_user
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    def employer?
    if !current_user.employer
      redirect_to :jobs, :alert => "Hi there, it seems that you might be lost!"
    end
    end

    def own_job?
    if @job.employer_id != current_user.employer_id
      redirect_to :jobs, :alert => "Hi there, it seems that you might be lost!"
    end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:title, :description, :wage, :employer_id, :contact_person, :contact_number, :contact_email, :device, :software, :skills, :job_type, :duration, :time_commitment, :training, :location, :positions, :start_date)
    end

    def search(search)
    if search
      Job.where('title ILIKE ?', "%#{search}%")
    end
    end


    # def job_filled?
    #   if @job.employee
    #     redirect_to :job, :alert => "Sorry, the job cannot be changed once post has been filled"
    #   end
    # end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_accordion-search.html.erb
<div class="container-fluid">

  <% if jobs_searched.empty? %>
  <p>No jobs match your search</p>
  <%else%>
  <% jobs_searched.each do |job_searched| %>
  <div id="accordion3" role="tablist" aria-multiselectable="true">
    <div class="card">
      <div class="card-header" role="tab" id="headingOne">
        <h5 class="mb-0">
          <a data-toggle="collapse" data-parent="#accordion3" href="#collapse<%=job_searched.id.to_s%>" aria-expanded="true" aria-controls="collapseOne">
            <%= job_searched.title %>
          </a>
        </h5>
      </div>

      <div id="collapse<%=job_searched.id.to_s%>" class="collapse" role="tabpanel" aria-labelledby="headingOne">
        <div class="card-block">
            <p>Company: <%= job_searched.employer.company %></p>
            <p>Description: <%= job_searched.description %></p>
            <p>Salary: <%= job_searched.wage %> / hr</p>
            <p>Contact person: <%= job_searched.contact_person %></p>
            <p>Contact number: <%= job_searched.contact_number %></p>
            <p>Contact email: <%= job_searched.contact_email %></p>
            <p>Device required: <%= job_searched.device %></p>
            <p>Software required: <%= job_searched.software %></p>
            <p>Skills required: <%= job_searched.skills %></p>
            <p>Job type: <%= job_searched.job_type %></p>
            <p>Job duration: <%= job_searched.duration %></p>
            <p>Time Commitment: <%= job_searched.time_commitment %> hrs / day</p>
            <p>Training required: <%= job_searched.training %></p>
            <p>Location: <%= job_searched.location %></p>
            <p>Start date: <%= job_searched.start_date %></p>
            <% hired_count = JobApplication.where(job_id: job_searched.id, status: 'Successful').count %>
            <p>No. of vacancies: <%= (job_searched.positions - hired_count) %></p>
            <% has_applied = false %>
            <% job_searched.job_applications.each do |job_applic| %>
            <% if job_applic.employee_id == current_user.employee_id %>
              <% has_applied = true %>
                <p>Status: <%= job_applic.status%> </p>
                <p><%= link_to "View Job Application", job_application_path(job_applic.id), class: "btn btn-primary" %></p>
            <% end %>
            <% end %>
            <% if has_applied == false && job_searched.positions - hired_count != 0 %>
                <%= form_for :job_application, url: job_applications_path do |f| %>
                <%= label :coverletter, "Please provide a short Coverletter in the text box below:", :class => "required"%>
                <%= f.text_area :coverletter, size: "40x5" %></p>
                <%= f.hidden_field :job_id, value: job_searched.id %>
                <%= f.hidden_field :employee_id, value: current_user.employee_id %>
                <%= f.hidden_field :status, value: "In Progress" %>
                <p><%= f.submit 'Apply', class:"btn btn-primary" %></p>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <% end %>
      <% end %>
    </div>

app/views/jobs/_employee-profile.html.erb
<h3>Your Profile</h3>
<div class="container-fluid">
  <p>Email Address: <%= current_user.email %></p>
  <p>Total Number of job applications: <%= current_user.employee.job_applications.count %></p>
  <p>Average Rating: </p>
</div>

app/views/jobs/_form.html.erb
<% if current_user.role == 'employer' %>
<%= bootstrap_form_for(@job) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :employer_id, value: current_user.employer_id %>
  <br/>
  <div class="card">
  <div class="card-block">
    <h4 class="card-title">Job Details</h4>
    <h6 class="card-subtitle mb-2 text-muted">Basic job information</h6>
    <p class="card-text">
      <div class='col-xs-12 col-md-6'><%= f.text_field :title, label: 'Job title' %></div>
      <div class='col-xs-12 col-md-6'><%= f.text_area :description, label: 'Description', placeholder: "Please provide details of the job scope" %></div>
      <div class='col-xs-12 col-md-6'><%= f.text_area :location, label: 'Job Location'%></div>
      <div class='col-xs-12 col-md-6'><%= f.text_field :wage, label: 'Hourly wage', placeholder: "Enter numbers only" %></div>
      <div class='col-lg-6'>
        <%= label :job_type, "Job Type", :class => "required"%>
        <span class="input-group"><%= f.radio_button :job_type, "Full-time" %> Full-time</span>
        <span class="input-group"><%= f.radio_button :job_type, "Contract" %> Contract</span>
      </div>
      <br />
      <div class='col-xs-12 col-md-6'><%= f.text_field :duration, label: 'Job duration (under contract in Months)'%></div>
      <div class='col-xs-12 col-md-6'><%= f.text_field :time_commitment, label: 'Working hours (Hours/day)'%></div>
      <div class='col-xs-12 col-md-6'><%= f.text_field :positions, label: 'No. of vacancies', placeholder: "Enter numbers only" %></div>
      <div class='col-xs-12 col-md-6'><%= f.text_field :start_date, label: 'Expected Start date', placeholder: "Eg. Immediate" %></div>
    </p>
    <br />
    <h4 class="card-title">Skills</h4>
    <h6 class="card-subtitle mb-2 text-muted">Technical and training requirements</h6>
    <p class="card-text">
        <div class='col-xs-12 col-md-6'><%= f.text_area :device, label: 'Device required', placeholder: "Eg. Computers, handphone etc." %></div>
        <div class='col-xs-12 col-md-6'><%= f.text_area :software, label: 'Software required' %></div>
        <div class='col-xs-12 col-md-6'><%= f.text_area :skills, label: 'Skills required', placeholder: "Eg. Able to speak basic English" %></div>
        <div class='col-xs-12 col-md-6'><%= f.text_area :training, label: 'Specific training required'%></div>
    </p>
    <br/>
    <h4 class="card-title">Contact Information</h4>
    <p class="card-text">
        <div class='col-xs-12 col-md-6'><%= f.text_field :contact_person, label: 'Contact Person'%></div>
        <div class='col-xs-12 col-md-6'><%= f.text_field :contact_number, label: 'Contact Number' %></div>
        <div class='col-xs-12 col-md-6'><%= f.text_field :contact_email, label: 'Contact Email' %></div>
        <div class='col-xs-12 col-md-6'><%= f.submit "Submit", class: 'btn btn-success' %></div>
    </p>
  </div>
  </div>
</div>


<% end %>
<% else %>
  <p>You must be an employer to view this page</p>
<% end %>

app/views/jobs/edit.html.erb
<h1>Editing Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
  <%if current_user.role == 'employer'%>
    <div class="container-fluid">
      <h4>JOB LIST
        <%= link_to new_job_path, class: "btn btn-default" do %>
          <i class="fa fa-plus-circle fa-2x" aria-hidden="true"></i>
        <% end %>
      </h4>

      <% @jobs.each_with_index do |job,i|%>
        <div class="container-fluid">
          <div class="card card-block">
          <h4 class="card-title">
            <span class="badge badge-pill badge-success"><%=job.job_applications.count%></span>
            <%= link_to job.title, job_path(job) %>
            <% if @vacancies_list[i] == 0 %>
              <span class="badge badge-pill badge-success pull-right">Filled</span>
            <%else%>
              <span class="badge badge-pill badge-warning col-xs-1 col-md-1 pull-right"><%= @hired_list[i] %> / <%= job.positions %></span>
            <% end %>
          </h4>
          </div>
        </div>
      <%end%>

    </div>

    <%elsif current_user.role == 'employee'%>
    <div id="the-basics" class="row">
      <%= form_tag(search_results_path, method: 'get', remote: true) do %>
        <p>
          <%= text_field_tag :search, params[:search], class:"typeahead", placeholder: "Enter job title" %>
          <%= submit_tag "Search Jobs", :title => nil, class:"btn btn-primary"%>
        </p>
      </div>
      <% end %>

      <div id="jobs-searched"></div>
      <br>

      <div class="container-fluid">
        <h4>MY APPLICATIONS</h4>
        <% @job_applications_made.each do |job_app| %>
          <div id="accordion1" role="tablist" aria-multiselectable="true">
            <div class="card">
              <div class="card-header" role="tab" id="headingOne">
                <h5 class="mb-0">
                  <a data-toggle="collapse" data-parent="#accordion1" href="#collapseOne<%=job_app.job.id.to_s%>" aria-expanded="true" aria-controls="collapseOne">
                    <%= job_app.job.title %>
                    <% if job_app.status == "Successful" %>
                    <span class="badge badge-success">Hired</span>
                    <%elsif job_app.status == "In Progress" %>
                    <span class="badge badge-warning">Pending</span>
                    <%else%>
                    <span class="badge badge-danger">Unsuccessful</span>
                    <%end%>
                  </a>
                </h5>
              </div>

              <div id="collapseOne<%= job_app.job.id.to_s%>" class="collapse" role="tabpanel" aria-labelledby="headingOne">
                <div class="card-block">

                  <h4 class="card-title">Job Details</h4>
                  <h6 class="card-subtitle mb-2 text-muted">Basic job information</h6>

                  <p><strong>Company: </strong><%= job_app.job.employer.company %></p>
                  <p><strong>Description: </strong><%= job_app.job.description %></p>
                  <p><strong>Location: </strong><%= job_app.job.location %></p>
                  <p><strong>Salary: </strong><%= job_app.job.wage %>/hr</p>
                  <p><strong>Job type: </strong><%= job_app.job.job_type %></p>
                  <p><strong>Job duration: </strong><%= job_app.job.duration %></p>
                  <p><strong>Time Commitment: </strong><%= job_app.job.time_commitment %> hrs / day</p>
                  <p><strong>Start date: </strong><%= job_app.job.start_date %></p>

                  <h4 class="card-title">Skills</h4>
                  <h6 class="card-subtitle mb-2 text-muted">Technical and training requirements</h6>

                  <p><strong>Device required: </strong><%= job_app.job.device %></p>
                  <p><strong>Software required: </strong><%= job_app.job.software %></p>
                  <p><strong>Skills required: </strong><%= job_app.job.skills %></p>
                  <p><strong>Training required: </strong><%= job_app.job.training %></p>

                  <h4 class="card-title">Contact Information</h4>

                  <p><strong>Contact person: </strong><%= job_app.job.contact_person %></p>
                  <p><strong>Contact email: </strong><%= job_app.job.contact_email %></p>
                    <p><%= link_to "View Job Application", job_application_path(job_app.id), class: "btn btn-primary" %></p>

                    </div>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        <br/>
      <div class="container-fluid">
          <h4>BROWSE JOBS</h4>

            <%if @jobs_not_applied.length ==0%>
          <br><h6>No jobs currently available</h6><br>
          <%else%>
          <% @job_opportunities.each_with_index do |job_new, i| %>
          <div id="accordion2" role="tablist" aria-multiselectable="true">
          <div class="card">
            <div class="card-header" role="tab" id="headingOne">
              <h5 class="mb-0">
                <a data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo<%=job_new.id.to_s%>" aria-expanded="true" aria-controls="collapseOne">
                  <%= job_new.title %>
                </a>
              </h5>
            </div>

            <div id="collapseTwo<%=job_new.id.to_s%>" class="collapse" role="tabpanel" aria-labelledby="headingOne">
              <div class="card-block">
                <h4 class="card-title">Job Details</h4>
                <h6 class="card-subtitle mb-2 text-muted">Basic job information</h6>

                <p><strong>Company: <%=link_to "#{job_new.employer.company}", employer_path(job_new.employer.id)%></p>
                <p><strong>Description: </strong><%= job_new.description %></p>
                <p><strong>Location: </strong><%= job_new.location %></p>
                <p><strong>Salary: </strong><%= job_new.wage %>/hr</p>
                <p><strong>Job type: </strong><%= job_new.job_type %></p>
                <p><strong>Job duration: </strong><%= job_new.duration %></p>
                <p><strong>Time Commitment: </strong><%= job_new.time_commitment %> hrs / day</p>
                <p><strong>No. of vacancies: </strong><%= @vacancies[i] %></p>
                <p><strong>Start date: </strong><%= job_new.start_date %></p>

                <h4 class="card-title">Skills</h4>
                <h6 class="card-subtitle mb-2 text-muted">Technical and training requirements</h6>

                <p><strong>Device required: </strong><%= job_new.device %></p>
                <p><strong>Software required: </strong><%= job_new.software %></p>
                <p><strong>Skills required: </strong><%= job_new.skills %></p>
                <p><strong>Training required: </strong><%= job_new.training %></p>

                <h4 class="card-title">Contact Information</h4>

                <p><strong>Contact person: </strong><%= job_new.contact_person %></p>
                <% if job_new.contact_number? %>
                <p><strong>Contact number: </strong><%= job_new.contact_number %></p>
                <% end %>
                <p><strong>Contact email: </strong><%= job_new.contact_email %></p>

                <%= form_for :job_application, url: job_applications_path do |f| %>
                <h4 class="card-title">Coverletter</h4>
                <%= label :coverletter, "Please provide a short Coverletter in the text box below to apply:", :class => "required"%>
                <%= f.text_area :coverletter, :class => "coverletter-box"%></p>
                <%= f.hidden_field :job_id, value: job_new.id %>
                <%= f.hidden_field :employee_id, value: current_user.employee_id %>
                <%= f.hidden_field :status, value: "In Progress" %>
                <p><%= f.submit 'Apply', class:"btn btn-primary"%></p>
                <% end %>
                  </div>
                </div>
              </div>
            </div>
            <% end %>
          <% end %>
        </div>
      <% end %>

<script>
var substringMatcher = function(strs) {
  return function findMatches(q, cb) {
    var matches, substringRegex;
    matches = [];
    substrRegex = new RegExp(q, 'i');
    $.each(strs, function(i, str) {
      if (substrRegex.test(str)) {
        matches.push(str);
      }
    });
    cb(matches);
  };
};

$('#the-basics .typeahead').typeahead({
  hint: true,
  highlight: true,
  minLength: 1
},
{
  name: 'title',
  source: substringMatcher(<%=@all_jobs.to_json.html_safe%>)
});
</script>

app/views/jobs/new.html.erb
<div class="container">
<h1>Create New Job</h1>


<%= render 'form', job: @job %>

</div>

app/views/jobs/searched.js.erb
$('#jobs-searched').html("<%= j (render partial: 'accordion-search', locals: {jobs_searched: @jobs_searched})  %>")

app/views/jobs/show.html.erb
<div class="card">

  <div class="card-header">
    <h4><%= @job.title %></h4>
    <h6 class="subtitle mb-2 text-muted margin"><%= @job.description %></p>
  </div>

  <div class="card-block row">

    <div class="col-md-6">
      <h4 class="card-title">Job Details</h4>
      <h6 class="card-subtitle mb-2 text-muted">Basic job information</h6>

      <p>
        <strong>Job location:</strong>
        <span class="text-blue"><%= @job.location%></span>
      </p>

      <p>
        <strong>Hourly Wage:</strong>
        <span class="text-blue">$<%= @job.wage %></span>
      </p>

      <p>
        <strong>Job type:</strong>
        <span class="text-blue"><%= @job.job_type %></span>
      </p>

      <p>
        <strong>Job duration:</strong>
        <span class="text-blue"><%= @job.duration %> Months</span>
      </p>

      <p>
        <strong>Working Hours:</strong>
        <span class="text-blue"><%= @job.time_commitment %> hours/day</span>
      </p>

      <p>
        <strong>Number of vacancies:</strong>
        <span class="text-blue"><%= @vacancies %></span>
      </p>

      <p>
        <strong>Start date:</strong>
        <span class="text-blue"><%= @job.start_date %></span>
      </p>

    <h4 class="card-title">Skills</h4>
    <h6 class="card-subtitle mb-2 text-muted">Technical and training requirements</h6>

      <p>
        <strong>Device required:</strong>
        <%= @job.device %>
      </p>

      <p>
        <strong>Software required:</strong>
        <%= @job.software %>
      </p>

      <p>
        <strong>Skills required:</strong>
        <%= @job.skills %>
      </p>

      <p>
        <strong>Specific training required:</strong>
        <%= @job.training %>
      </p>

    </div>

    <div class="col-md-6">
      <h4 class="card-title">Contact Information</h4>

      <p>
        <strong>Company:</strong>
        <%= @job.employer.company %>
      </p>

      <p>
        <strong>Contact Person:</strong>
        <%= @job.contact_person %>
      </p>

      <p>
        <strong>Contact Number:</strong>
        <%= @job.contact_number %>
      </p>

      <p>
        <strong>Contact Email:</strong>
        <%= @job.contact_email %>
      </p>
    </div>

    <div class="card-text">
      <p><strong>Number hired:</strong>
        <%= @hired.length %></p>

      <p><strong>Applicants:</strong>
        <%if @job_applications.length == 0%>
        No applicants yet.
        <%end%>
      </p>
    </div>
  </div>
</div>

<% @job_applications.each_with_index do |job_app,index|%>
<div id="accordion" role="tablist" aria-multiselectable="true">
  <div class="card">
    <div class="card-header" role="tab" id="headingOne">
      <h5 class="mb-0">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapse<%= index.to_s %>" aria-expanded="true" aria-controls="collapse<%= index.to_s %>">
          <%= job_app.employee.name %>
          <% if job_app.status == "Successful" %>
          <span class="badge badge-success">Hired</span>
          <%elsif job_app.status == "In Progress" %>
          <span class="badge badge-warning">Pending</span>
          <%else%>
          <span class="badge badge-danger">Rejected</span>
          <%end%>
        </a>
      </h5>
    </div>

    <div id="collapse<%= index.to_s %>" class="collapse" role="tabpanel" aria-labelledby="heading<%= index.to_s %>">
      <div class="card-block">

        <h4 class="card-title">Coverletter</h4>
        <p class="text-blue"><%=job_app.coverletter%></p>
        <p><strong>Contact Email:</strong> <%=job_app.employee.user.email%></p>
        <p><%= link_to 'View Profile', employee_path(job_app.employee_id), class:"btn btn-primary" %>
        <% if job_app.status == "In Progress" %>
        <%= link_to 'Hire', hire_path(job_app.id, "job_application[status]"=>"Successful"), method: :post, class:"btn btn-primary" %></p>
        <% elsif job_app.status == "Successful" && !job_app.rating_employee %>
        <%= link_to "Submit a Review", edit_job_application_path(job_app.id), class: "btn btn-primary" %></p>
        <% elsif job_app.status == "Successful" && job_app.rating_employee%>
        <%= link_to "Edit Your Review", edit_job_application_path, class: "btn btn-primary" %></p>
        <% end %>

      </div>
    </div>
  </div>
</div>
<% end %>
<br/>
<%= link_to "Edit", edit_job_path, class: "btn btn-primary"%>
<%= link_to 'Back', jobs_path, class: 'btn btn-primary' %>