config/routes.rb
Rails.application.routes.draw do
  # devise_for :controllers
  devise_for  :users, :controllers => {:registrations => "users/registrations"}

  resources :jobs

  resources :job_applications, :except => [:destroy]
  post '/job_applications/:id', to: 'job_applications#hire', as: 'hire'

  get "/search-results" => 'jobs#searched'
  # devise_for :employers, :controllers => {:registrations => "users/registrations"}
  # devise_for :employees
  resources :employers, :only => [:show]
  resources :employees, :only => [:show]

  root "static#homepage"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/employer.rb
class Employer < ApplicationRecord
  mount_uploader :image, ProfilePicUploader

  has_one :user
  has_many :jobs

end

app/controllers/employers_controller.rb
class EmployersController < ApplicationController
  before_action :set_employer, only: [:show, :edit, :update, :destroy]

  # GET /employers
  # GET /employers.json
  def index
    @employers = Employer.all
  end

  # GET /employers/1
  # GET /employers/1.json
  def show
   average_rating
   latest_three_reviews
  end

  # GET /employers/new
  def new
    @employer = Employer.new
  end

  # GET /employers/1/edit
  def edit
  end

  # POST /employers
  # POST /employers.json
  def create
    @employer = Employer.new(employer_params)

    respond_to do |format|
      if @employer.save
        format.html { redirect_to @employer, notice: 'Employer was successfully created.' }
        format.json { render :show, status: :created, location: @employer }
      else
        format.html { render :new }
        format.json { render json: @employer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employers/1
  # PATCH/PUT /employers/1.json
  def update
    respond_to do |format|
      if @employer.update(employer_params)
        format.html { redirect_to @employer, notice: 'Employer was successfully updated.' }
        format.json { render :show, status: :ok, location: @employer }
      else
        format.html { render :edit }
        format.json { render json: @employer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employers/1
  # DELETE /employers/1.json
  def destroy
    @employer.destroy
    respond_to do |format|
      format.html { redirect_to employers_url, notice: 'Employer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employer
      @employer = Employer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employer_params
      params.require(:employer).permit(:name, :company)
    end

    def average_rating
      @employer = Employer.find(params[:id])
      @total_rating = 0
      @total_reviews = 0
      @employer.jobs.each do |job|
        job.job_applications.where("status" == "successful").each do |application|
          @total_rating += application.rating_employer.to_i
          if application.rating_employer
          @total_reviews += 1
          end
        end
      end

      if @total_reviews.to_i > 0
      @average_rating = (@total_rating / @total_reviews).round(2)
      else
        @average_rating = 0
      end
    end

    def latest_three_reviews
      @employer = Employer.find(params[:id])
      @all_reviews = []
      @employer.jobs.each do |job|
      job.job_applications.each do |app|
        if app.rating_employer
          @all_reviews << app
        end
      end
    end
      @recent_reviews = @all_reviews.sort_by {|review| review.updated_at}
      @recent_reviews.reverse!.take(3)
    end

end

app/helpers/employers_helper.rb
module EmployersHelper
end

app/views/employers/_form.html.erb
<%= form_for(employer) do |f| %>
  <% if employer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employer.errors.count, "error") %> prohibited this employer from being saved:</h2>

      <ul>
      <% employer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :company %>
    <%= f.text_field :company %>
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employers/edit.html.erb
<h1>Editing Employer</h1>

<%= render 'form', employer: @employer %>

<%= link_to 'Show', @employer %> |
<%= link_to 'Back', employers_path %>

app/views/employers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Employers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Company</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employers.each do |employer| %>
      <tr>
        <td><%= employer.name %></td>
        <td><%= employer.company %></td>
        <td><%= link_to 'Show', employer %></td>
        <td><%= link_to 'Edit', edit_employer_path(employer) %></td>
        <td><%= link_to 'Destroy', employer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employer', new_employer_path %>

app/views/employers/new.html.erb
<h1>New Employer</h1>

<%= render 'form', employer: @employer %>

<%= link_to 'Back', employers_path %>

app/views/employers/show.html.erb
<%= render 'partials/employer-profile' %>

<%if @recent_reviews%>
<div class="card-deck">
  <%@recent_reviews.each do |review|%>
  <div class="card">
    <div class="card-block">
      <h4 class="card-title"><span id="star-rating"></span><span id="rating">Rating: <%=review.rating_employer%></span></h4>
      <p class="card-text"><p><i>"<%=review.review_employer%>"</i></p>
      <p><%=review.employee.name%>, <%=review.updated_at.strftime("%m/%d/%y")%></p>
      </p>
    </div>
  </div>
  <%end%>
</div>
<%end%>
<br />
<div class="container-fluid">
<%if @employer.user.id == current_user.id%>
<%= link_to 'Edit', edit_user_registration_path, :class => "btn btn-primary" %>
<%end%>
<%= link_to 'Back', jobs_path, :class => "btn btn-primary" %>
</div>